// Code generated by go-bindata.
// sources:
// a.graphql
// schema.graphql
// DO NOT EDIT!

package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _aGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x8e\x4d\x0e\xc2\x20\x14\x84\xd7\xf3\x4e\x81\xbb\x7a\x05\xf6\x26\x6e\x5c\x98\x9e\x00\x5b\xd2\x92\x14\x5a\xf9\x31\x21\xa6\x77\x37\x82\xb5\xcf\x8d\x2b\x98\xbc\x99\x6f\x06\xa1\x1b\xb5\x55\xe2\x49\x40\x48\xb7\xd0\x79\xb3\x44\x33\x3b\x29\x5a\xa6\x08\xb0\x29\xaa\x7a\xb8\x7c\x7e\x04\xdc\x93\xf6\x59\x8a\xeb\xfb\x21\xac\x84\x98\x17\x5d\x65\x21\x8e\x7a\x9a\x66\x29\xda\xe8\x8d\x1b\x0e\xbb\x83\xb3\x77\x63\xab\x4c\xdf\x1c\xa5\x38\x6f\xe2\xf4\xd0\x2e\xb2\xd8\xd6\x5c\xd7\xaa\x5c\x8c\x8d\x0d\xc3\xb7\xe2\x5f\xfa\xf7\x50\x18\xa6\x67\xe3\xc0\x41\x84\xf5\x15\x00\x00\xff\xff\xd8\x0e\x34\x73\x1b\x01\x00\x00")

func aGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_aGraphql,
		"a.graphql",
	)
}

func aGraphql() (*asset, error) {
	bytes, err := aGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "a.graphql", size: 283, mode: os.FileMode(436), modTime: time.Unix(1553124934, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schemaGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x8e\x4d\x0e\xc2\x20\x14\x84\xd7\xf3\x4e\x81\xbb\x7a\x05\xf6\x26\x6e\x5c\x98\x9e\x00\x5b\xd2\x92\x14\x5a\xf9\x31\x21\xa6\x77\x37\x82\xb5\xcf\x8d\x2b\x98\xbc\x99\x6f\x06\xa1\x1b\xb5\x55\xe2\x49\x40\x48\xb7\xd0\x79\xb3\x44\x33\x3b\x29\x5a\xa6\x08\xb0\x29\xaa\x7a\xb8\x7c\x7e\x04\xdc\x93\xf6\x59\x8a\xeb\xfb\x21\xac\x84\x98\x17\x5d\x65\x21\x8e\x7a\x9a\x66\x29\xda\xe8\x8d\x1b\x0e\xbb\x83\xb3\x77\x63\xab\x4c\xdf\x1c\xa5\x38\x6f\xe2\xf4\xd0\x2e\xb2\xd8\xd6\x5c\xd7\xaa\x5c\x8c\x8d\x0d\xc3\xb7\xe2\x5f\xfa\xf7\x50\x18\xa6\x67\xe3\xc0\x41\x84\xf5\x15\x00\x00\xff\xff\xd8\x0e\x34\x73\x1b\x01\x00\x00")

func schemaGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_schemaGraphql,
		"schema.graphql",
	)
}

func schemaGraphql() (*asset, error) {
	bytes, err := schemaGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema.graphql", size: 283, mode: os.FileMode(436), modTime: time.Unix(1553124934, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"a.graphql": aGraphql,
	"schema.graphql": schemaGraphql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"a.graphql": &bintree{aGraphql, map[string]*bintree{}},
	"schema.graphql": &bintree{schemaGraphql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

